export enum OrgStatus {
  ACTIVATED = "ACTIVATED",
  DEACTIVATED = "DEACTIVATED",
}
export enum OrgApproval {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
}


export enum OrgType {
  "GENERAL_ORGANIZATION" = "GENERAL",
  "PROJECT_PROPONENT" = "PROPONENT",
  "PROJECT_DEVELOPER" = "DEVELOPER",
  "MARKET_PARTICIPANT" = "PARTICIPANT",
  "OTHER" = "OTHERS",
}

export enum RoleInOrganization {
  FOUNDER = "FOUNDER",
  CEO = "CEO",
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  CFO = "CFO",
  CTO = "CTO",
  ACCOUNTANT = "ACCOUNTANT",
  DEVELOPER = "DEVELOPER",
  DESIGNER = "DESIGNER",
  SALES = "SALES",
  OTHER = "OTHER",
  COO = "COO",
  CPO = "CPO",
  C_SOMETHING = "C_SOMETHING",
  DIRECTOR = "DIRECTOR",
  EMPEROR = "EMPEROR",
  NOTHING_ON_THIS_LIST = "NOTHING_ON_THIS_LIST",
}
